# Default values for stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DataLink configuration
bifrost:

# CAOM-2 Metadata service configuration
sc2meta:

# CAOM-2 Repository service configuration
torkeep:

# CAOM-2 TAP query service configuration
argus:

# User Interface search configuration
search:
