# Default values for stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DataLink configuration
datalink:

# CAOM-2 Metadata service configuration
meta:

# CAOM-2 Repository service configuration
repo:

# CAOM-2 TAP query service configuration
tap:

# User Interface search configuration
search:
